# Generated by Django 4.1.5 on 2023-01-29 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus_branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(default='Zetech University', max_length=50)),
                ('campus_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='room_id',
            new_name='room_number',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='ending_time',
        ),
        migrations.AddField(
            model_name='bookings',
            name='ending_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='starting_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='starting_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='room',
            name='campus_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='room_booking_app.campus_branch'),
        ),
    ]
