# Generated by Django 4.1.2 on 2023-02-04 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_app', '0002_alter_booking_date_actioned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='actioned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_actioned', to=settings.AUTH_USER_MODEL),
        ),
    ]
