# Generated by Django 4.1.2 on 2023-02-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_app', '0003_alter_booking_actioned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='facilities_ids',
        ),
        migrations.AddField(
            model_name='rooms',
            name='facilities_ids',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
