# Generated by Django 4.1.5 on 2023-01-29 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_app', '0004_remove_bookings_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='room_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='room_booking_app.room'),
            preserve_default=False,
        ),
    ]
