# Generated by Django 4.1.2 on 2023-02-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_app', '0005_alter_rooms_facilities_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
