# Generated by Django 4.1.5 on 2023-01-29 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_app', '0005_bookings_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='ending_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
