# Generated by Django 4.1.2 on 2023-02-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_app', '0006_user_is_approver_user_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approver',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_default',
        ),
    ]
