# Generated by Django 4.1.5 on 2023-01-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_app', '0007_remove_bookings_ending_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
