# Generated by Django 4.1.2 on 2023-02-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_app', '0008_roles_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default=3, max_length=255),
        ),
    ]
