# Generated by Django 4.1.2 on 2023-02-15 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_app', '0011_remove_booking_is_approved_booking_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Room_Suspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('suspension_reason', models.CharField(blank=True, max_length=250)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_booking_app.rooms')),
            ],
        ),
    ]
