# Generated by Django 4.1.2 on 2023-02-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_app', '0012_rooms_is_suspended_room_suspension'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='suspension_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='suspension_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Room_Suspension',
        ),
    ]
