# Generated by Django 4.1.2 on 2023-02-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_app', '0014_room_suspension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='is_suspended',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='suspension_end',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='suspension_reason',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='suspension_start',
        ),
    ]
