# Generated by Django 4.1.2 on 2023-02-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_app', '0016_booking_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refreshments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='refreshments',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'approved'), (2, 'rejected'), (3, 'cancelled')], default=0),
        ),
    ]
