# Generated by Django 4.1.2 on 2023-02-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_app', '0019_booking_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extra_peripherals',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default=3, max_length=255),
        ),
    ]
