# Generated by Django 4.1.2 on 2023-03-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_app', '0021_alter_rooms_facilities_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshments',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role_name',
            field=models.CharField(max_length=100),
        ),
    ]
