# Generated by Django 4.1.2 on 2023-03-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_app', '0022_alter_refreshments_title_alter_roles_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='extra_peripherals',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='refreshments',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
